### ISSUE TITLE
Настроить Nuke для GitHub Actions

### ISSUE THREAD

**Issue by MihaMoor** [MihaMoor/Library#8]

**Comment by Axerm** [comment]
Есть такой фреймворк [Avalonia](https://avaloniaui.net/) "is a cross-platform UI framework for dotnet" ([репа](https://github.com/AvaloniaUI/Avalonia/tree/master)). Они используют `Nuke` для билдов. Если интересует, можно попытаться раскурить как это реализовано в нём. Хотя, не скрою, моя душа лежит больше к `PowerShell`)
